 import React, { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { AnimatePresence, motion } from "framer-motion";
import { Archive, BarChart3, Eye, MessageCircle, Music2, PawPrint, Send, Sparkles, Target, Trophy, Users, Wifi, X } from "lucide-react";

const url = (import.meta.env.VITE_SUPABASE_URL || "").replace(/\/rest\/v1\/?$/, "").trim();
const key = (import.meta.env.VITE_SUPABASE_ANON_KEY || "").trim();
const supabase = url.startsWith("https://") && url.includes(".supabase.co") && key.length > 20 ? createClient(url, key) : null;

const entriesRaw = [
  ["Denmark", "Søren Torpegaard Lund", "Før Vi Går Hjem"], ["Germany", "Sarah Engels", "Fire"], ["Israel", "Noam Bettan", "Michelle"], ["Belgium", "ESSYLA", "Dancing on the Ice"], ["Albania", "Alis", "Nân"],
  ["Greece", "Akylas", "Ferto"], ["Ukraine", "LELÉKA", "Ridnym"], ["Australia", "Delta Goodrem", "Eclipse"], ["Serbia", "LAVINA", "Kraj Mene"], ["Malta", "AIDAN", "Bella"],
  ["Czechia", "Daniel Zizka", "CROSSROADS"], ["Bulgaria", "DARA", "Bangaranga"], ["Croatia", "LELEK", "Andromeda"], ["United Kingdom", "LOOK MUM NO COMPUTER", "Eins, Zwei, Drei"],
  ["France", "Monroe", "Regarde!"], ["Moldova", "Satoshi", "Viva, Moldova!"], ["Finland", "Linda Lampenius x Pete Parkkonen", "Liekinheitin"], ["Poland", "ALICJA", "Pray"],
  ["Lithuania", "Lion Ceccah", "Sólo Quiero Más"], ["Sweden", "FELICIA", "My System"], ["Cyprus", "Antigoni", "JALLA"], ["Italy", "Sal Da Vinci", "Per Sempre Sì"],
  ["Norway", "JONAS LOVV", "YA YA YA"], ["Romania", "Alexandra Căpitănescu", "Choke Me"], ["Austria", "COSMÓ", "Tanzschein"],
];
const ENTRIES = entriesRaw.map(([country, artist, song]) => ({ country, artist, song }));
const emptyPrediction = { top1: "", top2: "", top3: "", top4: "", top5: "", last: "" };
const TOP_KEYS = ["top1", "top2", "top3", "top4", "top5"];
const OFFICIAL_RESULTS = { top1: "Bulgaria", top2: "Israel", top3: "Romania", top4: "Australia", top5: "Italy", last: "United Kingdom" };
const FLAGS = { Bulgaria: "🇧🇬", Israel: "🇮🇱", Romania: "🇷🇴", Australia: "🇦🇺", Italy: "🇮🇹", "United Kingdom": "🇬🇧" };
const SUMMARIES = {
  Bulgaria: "Bulgaria gewann mit einem energiegeladenen Pop-Auftritt, der moderne Club-Elemente mit folkloristischen Anklängen verbindet.",
  Israel: "Israel landete mit einer emotionalen Performance auf Platz 2.", Romania: "Rumänien erreichte Platz 3 mit einem dramatischen Pop-Rock-Auftritt.",
  Australia: "Australien überzeugte mit einer großen, professionellen Pop-Performance.", Italy: "Italien erreichte die Top 5 mit einer warmen, melodischen Nummer.",
  "United Kingdom": "Das Vereinigte Königreich landete auf dem letzten Platz.",
};
const RESULT_STORIES = [...TOP_KEYS.map((k, i) => ({ place: i + 1, country: OFFICIAL_RESULTS[k] })), { place: "Letzter Platz", country: OFFICIAL_RESULTS.last }]
  .map((r) => ({ ...r, ...ENTRIES.find((e) => e.country === r.country), summary: SUMMARIES[r.country] }));
const dogEffects = ["confetti", "fireworks", "sparkles", "lightbeams"];
const dogImages = ["Dackel", "Whippet", "Bulldogge"].flatMap((b) => [1, 2, 3].map((n) => ({ id: `${b.toLowerCase()}-${n}`, image: `/dogs/${b}-${n}.png` })));
const sheets = [{ breed: "Whippet", cols: 4, rows: 4, count: 16 }, { breed: "Bulldogge", cols: 3, rows: 3, count: 9 }, { breed: "Dackel", cols: 4, rows: 4, count: 16 }]
  .map((s) => ({ ...s, image: `/dogs/${s.breed}.png` }));
const hiddenDogIds = new Set(["whippet-1", "whippet-2", "whippet-3", "whippet-7", "whippet-9", "whippet-13", "whippet-15", "dackel-1", "dackel-4", "dackel-5", "dackel-10", "dackel-12", "dackel-13", "dackel-15"]);
const dogOptions = sheets
  .flatMap((s) => Array.from({ length: s.count }, (_, i) => ({ ...s, col: i % s.cols, row: Math.floor(i / s.cols), id: `${s.breed.toLowerCase()}-${i + 1}`, label: `${s.breed} ${i + 1}` })))
  .filter((d) => !hiddenDogIds.has(d.id));
const defaultDog = dogOptions[0]?.id || "";

const cn = (...xs) => xs.filter(Boolean).join(" ");
const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
const entryLabel = (country) => { const e = ENTRIES.find((x) => x.country === country); return e ? `${e.country} — ${e.artist} · “${e.song}”` : ""; };
const cleanPrediction = (p = {}) => Object.fromEntries([...TOP_KEYS, "last"].map((k) => [k, p[k] || ""]));

function Card({ children, className = "" }) { return <div className={cn("rounded-[2rem] border border-white/20 bg-white/15 text-white shadow-2xl backdrop-blur", className)}>{children}</div>; }
function Button({ children, className = "", ...props }) { return <button {...props} className={cn("inline-flex items-center justify-center rounded-full px-5 py-3 font-bold transition disabled:cursor-not-allowed disabled:opacity-60", className)}>{children}</button>; }
function SectionTitle({ icon: Icon, title, desc, className = "" }) { return <div className={cn("mb-4 flex items-center gap-3", className)}><Icon className="h-7 w-7 text-yellow-200" /><div><h2 className="text-2xl font-black md:text-4xl">{title}</h2>{desc && <p className="text-sm text-white/75 md:text-base">{desc}</p>}</div></div>; }

function Avatar({ dogId, name = "", size = "md", className = "", onClick }) {
  const dog = dogOptions.find((d) => d.id === dogId) || dogOptions[0];
  const sizeClass = size === "lg" ? "h-28 w-28" : size === "sm" ? "h-16 w-16" : "h-20 w-20";
  const style = dog ? {
    backgroundImage: `url(${dog.image})`,
    backgroundPosition: `${dog.cols === 1 ? 0 : (dog.col / (dog.cols - 1)) * 100}% ${dog.rows === 1 ? 0 : (dog.row / (dog.rows - 1)) * 100}%`,
    backgroundSize: `${dog.cols * 100}% ${dog.rows * 100}%`,
    transform: "scale(0.86)",
    transformOrigin: "center",
  } : {};
  const content = dog ? <span className="flex h-full w-full items-center justify-center rounded-[1.4rem] bg-white p-[6%]"><span aria-hidden className="block h-full w-full bg-contain bg-center bg-no-repeat" style={style} /></span> : <span className="flex h-full w-full items-center justify-center rounded-[1.4rem] bg-white/90 text-xl">🐶</span>;
  const cls = cn(sizeClass, "shrink-0 overflow-hidden rounded-[1.6rem] border-4 border-white/80 bg-white", onClick ? "shadow-xl ring-2 ring-fuchsia-300/60 transition hover:scale-105 hover:ring-yellow-200" : "shadow-lg", className);
  return onClick ? <button type="button" onClick={onClick} className={cls} title={name ? `Profilbild von ${name} ändern` : "Profilbild ändern"}>{content}</button> : <div className={cls}>{content}</div>;
}

function DogPicker({ open, selectedId, onSelect, onClose }) {
  if (!open) return null;
  return <AnimatePresence><motion.div className="fixed inset-0 z-[1000] flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
    <motion.div initial={{ scale: .92, opacity: 0, y: 30 }} animate={{ scale: 1, opacity: 1, y: 0 }} exit={{ scale: .92, opacity: 0, y: 20 }} className="max-h-[92vh] w-full max-w-6xl overflow-auto rounded-[2rem] border border-white/20 bg-[#24105f]/95 p-6 text-white shadow-2xl">
      <div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-4xl font-black">Profilbild wählen</h2><p className="mt-1 text-white/80">Klick auf eine Pose, um sie als Profilbild zu speichern.</p></div><button onClick={onClose} className="flex h-11 w-11 items-center justify-center rounded-full bg-white/15 hover:bg-white/25"><X /></button></div>
      {sheets.map((s) => <section key={s.breed} className="mb-7"><h3 className="mb-3 text-2xl font-black">{s.breed}</h3><div className="grid grid-cols-3 gap-3 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8 xl:grid-cols-9">
        {dogOptions.filter((d) => d.breed === s.breed).map((d) => <button key={d.id} onClick={() => onSelect(d.id)} className={cn("rounded-[1.4rem] border p-3 transition hover:-translate-y-1 hover:bg-white/20", selectedId === d.id ? "border-yellow-300 bg-yellow-300/25 ring-4 ring-yellow-300/40" : "border-white/15 bg-white/10")}><Avatar dogId={d.id} size="lg" className="mx-auto" /></button>)}
      </div></section>)}
    </motion.div>
  </motion.div></AnimatePresence>;
}

function SelectEntry({ value, onChange, label, used = [] }) {
  return <label className="block"><span className="mb-2 block text-sm font-black text-white/95">{label}</span><select value={value || ""} onChange={(e) => onChange(e.target.value)} className="w-full rounded-xl border border-white/30 bg-white/95 px-4 py-3 text-sm text-slate-900 shadow-sm outline-none transition focus:ring-4 focus:ring-fuchsia-300">
    <option value="">Bitte auswählen</option>{ENTRIES.map((e) => <option key={e.country} value={e.country} disabled={used.includes(e.country) && value !== e.country}>{e.country} — {e.artist} · {e.song}</option>)}
  </select></label>;
}

function CelebrationEffect({ type }) {
  const dots = (n, cls, style = () => ({}), props = () => ({})) => <div className="absolute inset-0 overflow-hidden">{Array.from({ length: n }, (_, i) => <motion.span key={i} className={cls} style={style(i)} {...props(i)} />)}</div>;
  if (type === "fireworks") return <div className="absolute inset-0 overflow-hidden">{Array.from({ length: 9 }, (_, i) => <motion.div key={i} className="absolute h-2 w-2 rounded-full bg-white shadow-[0_0_24px_rgba(255,255,255,.95)]" style={{ left: `${12 + (i * 10) % 82}%`, top: `${12 + (i * 17) % 62}%` }} initial={{ scale: 0, opacity: 0 }} animate={{ scale: [0, 1.1, 0], opacity: [0, 1, 0] }} transition={{ duration: 1.25, delay: i * .08 }}>{Array.from({ length: 10 }, (_, j) => <motion.span key={j} className="absolute left-1/2 top-1/2 h-1 w-12 origin-left rounded-full bg-gradient-to-r from-yellow-200 via-fuchsia-300 to-transparent" style={{ rotate: `${j * 36}deg` }} initial={{ scaleX: 0 }} animate={{ scaleX: [0, 1, 0] }} transition={{ duration: 1.2, delay: i * .08 }} />)}</motion.div>)}</div>;
  if (type === "lightbeams") return dots(8, "absolute left-1/2 top-1/2 h-[150vh] w-16 origin-bottom rounded-full bg-gradient-to-t from-white/30 via-fuchsia-300/20 to-transparent blur-xl", (i) => ({ rotate: `${i * 45}deg` }), (i) => ({ initial: { opacity: 0, scaleY: .25 }, animate: { opacity: [0, .8, 0], scaleY: [.25, 1, .4] }, transition: { duration: 1.8, delay: i * .04 } }));
  if (type === "sparkles") return <div className="absolute inset-0 overflow-hidden">{Array.from({ length: 70 }, (_, i) => <motion.span key={i} className="absolute text-2xl" style={{ left: `${Math.random() * 100}%`, top: `${Math.random() * 100}%` }} initial={{ opacity: 0, scale: 0, rotate: 0 }} animate={{ opacity: [0, 1, 0], scale: [0, 1.3, 0], rotate: 180 }} transition={{ duration: 1.5, delay: Math.random() * .7 }}>✨</motion.span>)}</div>;
  return dots(95, "absolute h-4 w-4 rounded-sm", (i) => ({ background: ["#ff4fd8", "#ffe45e", "#39d7ff", "#a3ff53", "#ff8a3d"][i % 5] }), () => ({ initial: { y: -80, x: `${Math.random() * 100}vw`, opacity: 0, rotate: 0, scale: .6 }, animate: { y: "105vh", opacity: [0, 1, 1, 0], rotate: 720, scale: [.6, 1, .8] }, transition: { duration: 1.7 + Math.random(), delay: Math.random() * .35, ease: "easeOut" } }));
}

function DogCelebration({ dog, message }) {
  if (!dog) return null;
  return <AnimatePresence><motion.div className="pointer-events-none fixed inset-0 z-[999] flex items-center justify-center overflow-hidden bg-black/45 backdrop-blur-sm" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><CelebrationEffect type={dog.effect || "confetti"} /><motion.div initial={{ scale: .72, opacity: 0, y: 40 }} animate={{ scale: 1, opacity: 1, y: 0 }} exit={{ scale: .84, opacity: 0, y: -35 }} className="relative flex flex-col items-center"><motion.img src={dog.image} alt="" draggable="false" animate={{ rotate: [0, -2, 2, 0], scale: [.96, 1.02, 1] }} className="max-h-[72vh] max-w-[78vw] select-none object-contain drop-shadow-[0_25px_50px_rgba(0,0,0,.65)]" /><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mt-5 rounded-full border border-white/20 bg-white/15 px-7 py-3 text-center text-2xl font-black text-white shadow-2xl backdrop-blur-xl">{message}</motion.div></motion.div></motion.div></AnimatePresence>;
}

function scorePrediction(prediction = emptyPrediction, results = OFFICIAL_RESULTS) {
  const top5 = TOP_KEYS.map((k) => results[k]).filter(Boolean); let total = 0;
  const rows = TOP_KEYS.map((k, i) => { const pick = prediction[k]; const points = !pick ? 0 : pick === results[k] ? 10 : top5.includes(pick) ? 5 : 0; total += points; return { label: `Platz ${i + 1}`, pick, points, reason: points === 10 ? "Top-5-Act auf richtigem Platz" : points === 5 ? "Top-5-Treffer, aber anderer Platz" : pick ? "nicht in den Top 5" : "–", correct: points === 10, partial: points === 5 }; });
  [["Siegertipp", "top1", results.top1, 30], ["Letzter Platz", "last", results.last, 20]].forEach(([label, key, target, value]) => { if (!prediction[key]) return; const points = prediction[key] === target ? value : 0; total += points; rows.push({ label, pick: prediction[key], points, reason: points ? `richtig${label === "Siegertipp" ? "er Siegertipp" : "er letzter Platz"}` : label === "Siegertipp" ? "nicht Sieger" : "nicht letzter Platz", correct: points > 0, partial: false }); });
  return { total, rows, exact: rows.filter((r) => r.correct).length, partial: rows.filter((r) => r.partial).length };
}

function Progress({ value, max, animated = false }) {
  const width = `${Math.max(5, (value / Math.max(1, max)) * 100)}%`;
  return <div className="h-3 overflow-hidden rounded-full bg-black/30">{animated ? <motion.div className="h-full rounded-full bg-gradient-to-r from-lime-300 via-yellow-300 to-fuchsia-300" initial={{ width: 0 }} animate={{ width }} /> : <div className="h-full rounded-full bg-gradient-to-r from-lime-300 via-yellow-300 to-fuchsia-300" style={{ width }} />}</div>;
}

function PlayerCard({ player, avatar, maxScore, compact = false }) {
  return <div className="rounded-2xl bg-white/12 p-4"><div className="mb-2 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Avatar dogId={avatar} name={player.name} size="sm" /><div className="flex h-12 w-12 items-center justify-center rounded-full bg-white text-xl font-black text-fuchsia-700">{player.rank}</div><div><div className={compact ? "text-2xl font-black" : "text-3xl font-black"}>{player.name}</div><div className="text-xs text-white/70">{player.exact} Volltreffer · {player.partial} Top-5-Treffer</div></div></div><div className="text-right"><div className="text-3xl font-black text-yellow-200">{player.total}</div><div className="text-xs font-bold uppercase tracking-widest text-white/70">Punkte</div></div></div><Progress value={player.total} max={maxScore} animated={!compact} />{!compact && <div className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{player.rows.map((r) => <div key={`${player.name}-${r.label}`} className="rounded-2xl bg-black/18 p-3"><div className="flex items-center justify-between gap-3"><div className="font-black">{r.label}</div><div className={cn("rounded-full px-3 py-1 text-sm font-black", r.points ? "bg-yellow-300 text-slate-950" : "bg-white/10 text-white/75")}>{r.points}</div></div><div className="mt-1 text-sm text-white/85">{r.pick ? entryLabel(r.pick) : "kein Tipp"}</div><div className="mt-1 text-xs text-white/60">{r.reason}</div></div>)}</div>}</div>;
}

function ResultsGrid({ archive = false }) {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{RESULT_STORIES.map((r) => <div key={`${archive}-${r.country}`} className="rounded-[2rem] bg-white/10 p-4">{archive ? <div className="mb-3 flex items-center gap-4"><div className="text-5xl">{FLAGS[r.country] || "🏳️"}</div><div><div className="text-sm font-black text-cyan-200">{typeof r.place === "number" ? `${r.place}. Platz` : r.place}</div><div className="text-2xl font-black">{r.country}</div></div></div> : <div className="relative flex h-44 items-center justify-center overflow-hidden rounded-3xl bg-gradient-to-br from-white/20 via-purple-800/35 to-cyan-500/25 shadow-inner"><motion.div initial={{ scale: .86, rotate: -4 }} animate={{ scale: [.86, 1.02, 1], rotate: [-4, 2, 0] }} className="text-[7rem] leading-none">{FLAGS[r.country] || "🏳️"}</motion.div></div>}<div className={archive ? "" : "mt-4"}><div className="text-sm font-black text-cyan-200">{typeof r.place === "number" ? `${r.place}. Platz` : r.place}</div><h3 className="text-2xl font-black">{r.country}</h3><p className="font-bold text-white/90">{r.artist} · “{r.song}”</p></div>{!archive && <p className="mt-3 text-sm leading-relaxed text-white/85">{r.summary}</p>}</div>)}</div>;
}

function PointsOverview() {
  return <Card className="p-6"><SectionTitle icon={Target} title="Punkteübersicht" desc="So werden die Tipps im Hundefreunde Wettstudio gewertet." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[[30, "Richtiger Siegertipp", "Dein Platz-1-Tipp ist automatisch dein Siegertipp."], [20, "Richtiger letzter Platz", "Du hast den Act auf dem letzten Platz korrekt getippt."], [10, "Top 5 exakt", "Ein Act ist in den Top 5 und genau auf dem richtigen Platz."], [5, "Top 5 Treffer", "Ein Act ist in den Top 5, aber auf einem anderen Platz als getippt."]].map(([points, title, desc]) => <div key={title} className="rounded-[2rem] bg-white/10 p-5 text-center"><div className="mx-auto mb-3 flex h-20 w-20 items-center justify-center rounded-full bg-yellow-300 text-3xl font-black text-slate-950">{points}</div><h3 className="text-xl font-black">{title}</h3><p className="mt-2 text-sm text-white/80">{desc}</p></div>)}</div></Card>;
}

export default function ESC2026Tippspiel() {
  const [players, setPlayers] = useState([]), [predictions, setPredictions] = useState({}), [currentName, setCurrentName] = useState(() => localStorage.getItem("esc2026_currentName") || ""), [selectedPlayer, setSelectedPlayer] = useState(""), [nameInput, setNameInput] = useState(""), [view, setView] = useState("vote"), [status, setStatus] = useState("Live-Verbindung wird aufgebaut …"), [draft, setDraft] = useState(emptyPrediction), [activeDog, setActiveDog] = useState(null), [dogMessage, setDogMessage] = useState(""), [chatMessages, setChatMessages] = useState([]), [chatInput, setChatInput] = useState(""), [scoreKey, setScoreKey] = useState(0), [pickerOpen, setPickerOpen] = useState(false);
  const [avatars, setAvatars] = useState(() => { try { return JSON.parse(localStorage.getItem("esc2026_profilePictures") || "{}"); } catch { return {}; } });
  const avatar = (name) => avatars[name] || defaultDog;
  const showDog = (message = "Gespeichert!") => { setDogMessage(message); setActiveDog({ ...pick(dogImages), effect: pick(dogEffects) }); setTimeout(() => { setActiveDog(null); setDogMessage(""); }, 2300); };
  const openView = (v) => { setView(v); if (v === "score") setScoreKey((x) => x + 1); };
  const db = (table) => supabase.from(table);

  async function refreshAll() {
    if (!supabase) return setStatus("Nicht verbunden: Vercel Supabase Variablen prüfen");
    const [p, t, c, a] = await Promise.all([db("esc2026_players").select("name, created_at").order("created_at", { ascending: true }), db("esc2026_predictions").select("*"), db("esc2026_chat").select("id, player_name, message, created_at").order("created_at", { ascending: true }).limit(120), db("esc2026_profiles").select("player_name, avatar_id")]);
    if (p.error || t.error) return setStatus(`Nicht verbunden: ${p.error?.message || t.error?.message || "Supabase prüfen"}`);
    setPlayers((p.data || []).map((x) => x.name)); setPredictions(Object.fromEntries((t.data || []).map((x) => [x.player_name, cleanPrediction(x)])));
    if (!a.error) setAvatars((prev) => { const merged = { ...prev, ...Object.fromEntries((a.data || []).filter((x) => x.avatar_id).map((x) => [x.player_name, x.avatar_id])) }; localStorage.setItem("esc2026_profilePictures", JSON.stringify(merged)); return merged; });
    setChatMessages(c.error ? [] : c.data || []); setStatus(c.error ? `Verbunden – Chat prüfen: ${c.error.message}` : "Verbunden mit Supabase ✓");
  }

  useEffect(() => { refreshAll(); const interval = setInterval(refreshAll, 3000); if (!supabase) return () => clearInterval(interval); const channel = supabase.channel("esc2026-live").on("postgres_changes", { event: "*", schema: "public", table: "esc2026_players" }, refreshAll).on("postgres_changes", { event: "*", schema: "public", table: "esc2026_predictions" }, refreshAll).on("postgres_changes", { event: "*", schema: "public", table: "esc2026_chat" }, refreshAll).subscribe(); return () => { clearInterval(interval); supabase.removeChannel(channel); }; }, []);
  useEffect(() => setDraft(predictions[currentName] || emptyPrediction), [currentName, predictions]);

  async function login() { const name = nameInput.trim(); if (!name || !supabase) return; if (!players.includes(name)) setPlayers((xs) => [...xs, name]); await db("esc2026_players").upsert({ name }, { onConflict: "name" }); await db("esc2026_predictions").upsert({ player_name: name, ...emptyPrediction, winner: "" }, { onConflict: "player_name" }); localStorage.setItem("esc2026_currentName", name); setCurrentName(name); setSelectedPlayer(name); setNameInput(""); showDog("Herzlich willkommen!"); refreshAll(); }
  async function savePrediction(next) { if (!currentName || !supabase) return; const cleaned = cleanPrediction(next); setDraft(cleaned); setPredictions((p) => ({ ...p, [currentName]: cleaned })); const { error } = await db("esc2026_predictions").upsert({ player_name: currentName, ...cleaned, winner: cleaned.top1, updated_at: new Date().toISOString() }, { onConflict: "player_name" }); error ? setStatus(`Speichern fehlgeschlagen: ${error.message}`) : (showDog("Tipps automatisch gespeichert!"), refreshAll()); }
  async function saveAvatar(dogId) { if (!currentName || !dogId) return; const next = { ...avatars, [currentName]: dogId }; setAvatars(next); localStorage.setItem("esc2026_profilePictures", JSON.stringify(next)); setPickerOpen(false); showDog("Profilbild gespeichert!"); if (supabase) { const { error } = await db("esc2026_profiles").upsert({ player_name: currentName, avatar_id: dogId, updated_at: new Date().toISOString() }, { onConflict: "player_name" }); error ? setStatus("Profilbild lokal gespeichert – für Live-Sync bitte Tabelle esc2026_profiles anlegen.") : refreshAll(); } }
  async function sendChat() { const message = chatInput.trim(); if (!message || !currentName || !supabase) return; setChatInput(""); const { error } = await db("esc2026_chat").insert({ player_name: currentName, message }); error ? (setStatus(`Chat konnte nicht gespeichert werden: ${error.message}`), setChatInput(message)) : refreshAll(); }
  async function applyOfficialResults() { if (supabase) await db("esc2026_results").upsert({ id: 1, ...OFFICIAL_RESULTS, winner: OFFICIAL_RESULTS.top1, updated_at: new Date().toISOString() }, { onConflict: "id" }); openView("score"); showDog("Ergebnis aktualisiert!"); }
  async function removePlayer(name) { if (!supabase || !name || !confirm(`${name} wirklich entfernen? Die Tipps dieser Person werden ebenfalls gelöscht.`)) return; await db("esc2026_predictions").delete().eq("player_name", name); await db("esc2026_players").delete().eq("name", name); if (currentName === name) { localStorage.removeItem("esc2026_currentName"); setCurrentName(""); setDraft(emptyPrediction); } if (selectedPlayer === name) setSelectedPlayer(""); refreshAll(); }
  const setDraftField = (k, v) => savePrediction({ ...draft, [k]: v });
  const choosePlayer = (name) => { setSelectedPlayer(name); setView("vote"); };
  const isOwnProfile = !selectedPlayer || selectedPlayer === currentName;

  const leaderboard = useMemo(() => {
    const sorted = players
      .map((name) => ({ name, ...scorePrediction(predictions[name]) }))
      .sort((a, b) => b.total - a.total || a.name.localeCompare(b.name));
    const scoreRanks = [...new Set(sorted.map((p) => p.total))].reduce((map, score, index) => ({ ...map, [score]: index + 1 }), {});
    return sorted.map((p) => ({ ...p, rank: scoreRanks[p.total] }));
  }, [players, predictions]);
  const maxScore = Math.max(1, ...leaderboard.map((p) => p.total));
  const winners = leaderboard.length ? leaderboard.filter((p) => p.total === leaderboard[0].total) : [];
  const viewed = predictions[selectedPlayer] || emptyPrediction;
  const usedTop = TOP_KEYS.map((k) => draft[k]).filter(Boolean);
  const nav = [["vote", currentName || "Tipps", PawPrint], ["results", "Ergebnis", Trophy], ["score", "Auswertung", BarChart3], ["points", "Punkteübersicht", Target], ["archive", "Archiv", Archive]];

  return <main className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top_left,_#ff2fb3,_transparent_30%),radial-gradient(circle_at_top_right,_#00d4ff,_transparent_26%),linear-gradient(135deg,_#1c0d5a,_#6616b8_45%,_#f0673b)] p-4 text-white md:p-8">
    <DogCelebration dog={activeDog} message={dogMessage} /><DogPicker open={pickerOpen} selectedId={avatar(currentName)} onSelect={saveAvatar} onClose={() => setPickerOpen(false)} />
    <div className="mx-auto max-w-[1720px]"><div className="grid gap-6 xl:grid-cols-[1fr_390px_390px]"><div>
      <motion.header initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="relative mb-5 min-h-[250px] overflow-hidden rounded-[2rem] border border-white/20 bg-white/15 p-7 shadow-2xl backdrop-blur"><motion.div animate={{ scale: [1, 1.03, 1] }} transition={{ repeat: Infinity, duration: 2.8 }} className="relative mb-2 inline-flex items-center gap-2 rounded-full bg-white/20 px-4 py-2 text-sm font-bold"><Sparkles className="h-4 w-4" /> ESC 2026 · Live Tipp-Wette</motion.div><div className="relative flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><h1 className="max-w-3xl text-5xl font-black leading-[.95] tracking-tight md:text-7xl">Hundefreunde Wettstudio ESC 2026</h1><p className="mt-4 max-w-2xl text-lg text-white/90">Gemeinsamer Tippstand, Live-Chat und automatische Speicherung auf allen Geräten.</p></div><div className="grid min-w-[250px] gap-3 text-sm md:text-right"><div className={cn("rounded-2xl p-4 font-bold", status.startsWith("Verbunden") ? "bg-lime-400/25" : "bg-white/20")}><Wifi className="mr-2 inline h-4 w-4" />{status}</div><div className="rounded-2xl bg-white/20 p-4 font-bold"><Users className="mr-2 inline h-4 w-4" />{players.length} Mitspieler:innen</div></div></div></motion.header>
      <div className="mb-5 flex flex-wrap gap-2">{nav.map(([id, label, Icon]) => <Button key={id} onClick={() => openView(id)} className={view === id ? "bg-white text-fuchsia-700 hover:bg-white" : "bg-white/20 text-white hover:bg-white/30"}><Icon className="mr-2 h-4 w-4" />{label}</Button>)}</div>

      {!currentName && view === "vote" && <Card className="mb-5 p-6"><h2 className="mb-2 text-3xl font-black">Einloggen zum Tippen</h2><p className="mb-4 text-white/80">Name eingeben oder rechts einen vorhandenen Namen anklicken.</p><div className="grid gap-3 md:grid-cols-[1fr_auto]"><input value={nameInput} onChange={(e) => setNameInput(e.target.value)} onKeyDown={(e) => e.key === "Enter" && login()} placeholder="Dein Name" className="rounded-2xl border border-white/30 bg-white/95 px-4 py-4 text-slate-900 outline-none focus:ring-4 focus:ring-fuchsia-300" /><Button onClick={login} disabled={!supabase || !nameInput.trim()} className="rounded-2xl bg-fuchsia-500 px-8 py-6 text-white hover:bg-fuchsia-600"><Music2 className="mr-2 h-4 w-4" />Los geht’s</Button></div></Card>}
      {currentName && view === "vote" && <Card className="p-6"><div className="mb-5 flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div className="flex items-center gap-4"><Avatar dogId={avatar(isOwnProfile ? currentName : selectedPlayer)} name={isOwnProfile ? currentName : selectedPlayer} size="lg" onClick={isOwnProfile ? () => setPickerOpen(true) : undefined} /><div><h2 className="text-3xl font-black">{isOwnProfile ? `Tipps von ${currentName}` : `Tipps von ${selectedPlayer}`} <span className="text-yellow-300">♛</span></h2><p className="text-white/90">{isOwnProfile ? "Jede Auswahl wird automatisch gespeichert. Platz 1 ist automatisch dein Siegertipp." : "Du kannst andere Mitspieler:innen ansehen, aber nur deinen eigenen Tipp bearbeiten."}</p>{isOwnProfile && <button onClick={() => setPickerOpen(true)} className="mt-2 rounded-full bg-white/15 px-4 py-2 text-sm font-black hover:bg-white/25">Profilbild ändern</button>}</div></div><Button onClick={() => { localStorage.removeItem("esc2026_currentName"); setCurrentName(""); setSelectedPlayer(""); }} className="bg-white/20 hover:bg-white/30"><Users className="mr-2 h-4 w-4" />Abmelden</Button></div><div className="grid gap-4 md:grid-cols-5">{TOP_KEYS.map((k, i) => <motion.div whileHover={{ y: -4 }} key={k} className="rounded-3xl bg-white/10 p-4"><SelectEntry label={`${i + 1}. Platz`} value={(isOwnProfile ? draft : viewed)[k]} used={isOwnProfile ? usedTop : []} onChange={(v) => isOwnProfile && setDraftField(k, v)} /></motion.div>)}</div><div className="mt-4 rounded-3xl bg-cyan-300/20 p-4 md:w-1/2"><SelectEntry label="Wer wird letzter? · 20 Punkte" value={(isOwnProfile ? draft : viewed).last} onChange={(v) => isOwnProfile && setDraftField("last", v)} /></div>{!isOwnProfile && <div className="mt-4 rounded-3xl border border-yellow-300/30 bg-yellow-300/10 p-4 text-sm font-bold text-yellow-100">Nur {currentName} kann diesen Tipp bearbeiten oder unter diesem Namen chatten.</div>}</Card>}
      {view === "results" && <Card className="p-6"><div className="mb-5 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-3xl font-black">Offizielles Ergebnis</h2><p className="text-white/80">Top 5 und letzter Platz mit Flaggen, Künstler:innen, Song und Kurzinfos.</p></div><Button onClick={applyOfficialResults} className="bg-lime-300 px-6 text-slate-950 hover:bg-lime-200"><Trophy className="mr-2 h-4 w-4" />Ergebnis übernehmen</Button></div><ResultsGrid /></Card>}
      {view === "points" && <PointsOverview />}
      {view === "archive" && <Card className="p-6"><SectionTitle icon={Archive} title="Archiv" desc="Alle abgeschlossenen ESC-Jahre werden hier gesammelt. Das aktuelle Ergebnis ist als Archivposter unter ESC 2026 abgelegt." /><div className="rounded-[2.5rem] border border-white/20 bg-gradient-to-br from-fuchsia-500/35 via-purple-700/40 to-cyan-400/25 p-6 shadow-2xl"><div className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><div className="mb-2 inline-flex rounded-full bg-white/20 px-4 py-2 text-sm font-black">Archivbild</div><h3 className="text-5xl font-black leading-none">ESC 2026</h3><p className="mt-2 text-white/80">Offizielles Hundefreunde-Wettstudio Ergebnis inklusive Endranking</p></div><div className="rounded-3xl bg-yellow-300 px-6 py-4 text-right text-slate-950"><div className="text-xs font-black uppercase tracking-widest">Sieger</div><div className="text-3xl font-black">🇧🇬 Bulgaria</div></div></div><ResultsGrid archive /><div className="mt-8 rounded-[2rem] bg-black/20 p-5"><SectionTitle icon={Trophy} title="Mitspieler-Ranking" desc="Archivierte Übersicht: Wer welchen Platz belegt hat und wie viele Punkte erreicht wurden." />{leaderboard.length ? <div className="space-y-3">{leaderboard.map((p) => <PlayerCard key={p.name} player={p} avatar={avatar(p.name)} maxScore={maxScore} compact />)}</div> : <div className="rounded-2xl bg-white/10 p-4 text-sm text-white/80">Noch keine Mitspieler:innen im Archiv vorhanden.</div>}</div></div></Card>}
      {view === "score" && <Card className="p-6"><div className="mb-6 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-4xl font-black">Live-Auswertung</h2><p className="text-white/80">Automatisch berechnet nach dem offiziellen Ergebnis.</p></div><Button onClick={() => setScoreKey((x) => x + 1)} className="bg-yellow-300 text-slate-950 hover:bg-yellow-200"><Sparkles className="mr-2 h-4 w-4" />Noch mal feiern</Button></div>{leaderboard.length ? <div className="space-y-4"><div className="rounded-[2rem] border border-yellow-200/40 bg-gradient-to-br from-yellow-300/30 via-fuchsia-400/20 to-cyan-300/20 p-6 text-center shadow-2xl"><div className="mb-2 text-sm font-black uppercase tracking-[0.3em] text-yellow-100">{winners.length > 1 ? "Gewinner:innen" : "Gewinner:in"}</div><div className="flex flex-wrap justify-center gap-5">{winners.map((w) => <motion.div key={`winner-${w.name}`} initial={{ scale: .9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="flex flex-col items-center"><Avatar dogId={avatar(w.name)} name={w.name} size="lg" /><div className="mt-3 text-4xl font-black md:text-6xl">{w.name}</div><div className="mt-1 rounded-full bg-yellow-300 px-5 py-2 text-xl font-black text-slate-950">{w.total} Punkte</div></motion.div>)}</div></div><AnimatePresence mode="popLayout">{leaderboard.map((p, i) => <motion.div key={`${scoreKey}-${p.name}`} layout initial={{ opacity: 0, x: -30, scale: .96 }} animate={{ opacity: 1, x: 0, scale: 1 }} transition={{ delay: i * .06 }}><PlayerCard player={p} avatar={avatar(p.name)} maxScore={maxScore} /></motion.div>)}</AnimatePresence></div> : <div className="rounded-3xl bg-white/10 p-6 text-white/80">Noch keine Mitspieler:innen vorhanden.</div>}</Card>}
    </div>

    <aside className="space-y-5"><Card className="p-5"><SectionTitle icon={Users} title="Mitspieler:innen" desc="Ansehen, übernehmen oder entfernen." />{players.length ? <div className="space-y-3">{players.map((name) => <div key={name} className={cn("rounded-2xl p-3 transition", selectedPlayer === name ? "bg-yellow-300/20 ring-2 ring-yellow-300/40" : "bg-white/10")}><div className="flex items-center gap-3"><Avatar dogId={avatar(name)} name={name} size="sm" /><div className="min-w-0 flex-1"><div className="truncate text-lg font-black">{name}</div><div className="text-xs text-white/65">{predictions[name]?.top1 ? `Siegertipp: ${predictions[name].top1}` : "noch kein Siegertipp"}</div></div></div><div className="mt-3 grid grid-cols-2 gap-2"><Button onClick={() => choosePlayer(name)} className="bg-white/15 px-3 py-2 text-xs hover:bg-white/25"><Eye className="mr-1 h-3 w-3" />Ansehen</Button>{name === currentName && <Button onClick={() => removePlayer(name)} className="bg-black/20 px-3 py-2 text-xs hover:bg-black/35"><X className="mr-1 h-3 w-3" />Löschen</Button>}</div></div>)}</div> : <div className="rounded-2xl bg-white/10 p-4 text-sm text-white/75">Noch niemand eingeloggt.</div>}</Card>
      <Card className="p-5"><SectionTitle icon={Eye} title="Tipp-Ansicht" desc={selectedPlayer || "Wähle rechts eine Person aus."} />{selectedPlayer ? <div className="space-y-2">{[...TOP_KEYS, "last"].map((k, i) => <div key={k} className={cn("rounded-2xl p-3", k === "last" ? "bg-cyan-300/15" : "bg-white/10")}><div className="text-xs font-black uppercase tracking-widest text-cyan-200">{k === "last" ? "Letzter Platz" : `${i + 1}. Platz`}</div><div className="font-bold">{viewed[k] ? entryLabel(viewed[k]) : "–"}</div></div>)}</div> : <div className="rounded-2xl bg-white/10 p-4 text-sm text-white/75">Noch keine Person ausgewählt.</div>}</Card></aside>

    <aside><Card className="flex max-h-[calc(100vh-4rem)] min-h-[680px] flex-col p-5"><SectionTitle icon={MessageCircle} title="Live-Chat" desc="Plaudern während des Tippens." /><div className="min-h-0 flex-1 space-y-3 overflow-auto rounded-[1.5rem] bg-black/18 p-3">{chatMessages.length ? chatMessages.map((m) => <div key={m.id} className="rounded-2xl bg-white/12 p-3"><div className="mb-1 flex items-center justify-between gap-3"><div className="font-black text-yellow-200">{m.player_name}</div><div className="text-[10px] text-white/50">{m.created_at ? new Date(m.created_at).toLocaleTimeString("de-DE", { hour: "2-digit", minute: "2-digit" }) : ""}</div></div><p className="whitespace-pre-wrap break-words text-sm text-white/90">{m.message}</p></div>) : <div className="rounded-2xl bg-white/10 p-4 text-sm text-white/75">Noch keine Nachrichten.</div>}</div><div className="mt-4 grid gap-2"><textarea value={chatInput} onChange={(e) => setChatInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendChat(); } }} placeholder={currentName ? "Nachricht schreiben …" : "Zum Chatten erst einloggen"} disabled={!currentName || !supabase} className="min-h-[90px] rounded-2xl border border-white/25 bg-white/95 p-3 text-slate-900 outline-none focus:ring-4 focus:ring-lime-300 disabled:opacity-60" /><Button onClick={sendChat} disabled={!chatInput.trim() || !currentName || !supabase} className="bg-lime-300 text-slate-950 hover:bg-lime-200"><Send className="mr-2 h-4 w-4" />Senden</Button></div></Card></aside>
    </div></div>
  </main>;
}
